// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    CheckGitlabTokenAuthGitlabTokenCheckPostData,
    CheckGitlabTokenAuthGitlabTokenCheckPostErrors,
    CheckGitlabTokenAuthGitlabTokenCheckPostResponses,
    GetGitlabUserUsersUserIdGetData,
    GetGitlabUserUsersUserIdGetErrors,
    GetGitlabUserUsersUserIdGetResponses,
    GetProfileAuthMeGetData,
    GetProfileAuthMeGetErrors,
    GetProfileAuthMeGetResponses,
    GetProjectMembersGitlabProjectsProjectIdMembersGetData,
    GetProjectMembersGitlabProjectsProjectIdMembersGetErrors,
    GetProjectMembersGitlabProjectsProjectIdMembersGetResponses,
    GetProjectPerformancePerformanceProjectProjectIdUsersUserIdGetData,
    GetProjectPerformancePerformanceProjectProjectIdUsersUserIdGetErrors,
    GetProjectPerformancePerformanceProjectProjectIdUsersUserIdGetResponses,
    GetTimeSpentStatisticsPerformanceusersUserIdTimeSpentGetData,
    GetTimeSpentStatisticsPerformanceusersUserIdTimeSpentGetErrors,
    GetTimeSpentStatisticsPerformanceusersUserIdTimeSpentGetResponses,
    GetUserPerformancePerformanceUsersUserIdGetData,
    GetUserPerformancePerformanceUsersUserIdGetErrors,
    GetUserPerformancePerformanceUsersUserIdGetResponses,
    GetUserSettingsPerformanceUsersUserIdSettingsGetData,
    GetUserSettingsPerformanceUsersUserIdSettingsGetErrors,
    GetUserSettingsPerformanceUsersUserIdSettingsGetResponses,
    GetUserTimelogsUsersUsernameTimelogsGetData,
    GetUserTimelogsUsersUsernameTimelogsGetErrors,
    GetUserTimelogsUsersUsernameTimelogsGetResponses,
    HealthHealthGetData,
    HealthHealthGetResponses,
    ListGitlabUsersUsersGetData,
    ListGitlabUsersUsersGetErrors,
    ListGitlabUsersUsersGetResponses,
    ListProjectsGitlabProjectsGetData,
    ListProjectsGitlabProjectsGetErrors,
    ListProjectsGitlabProjectsGetResponses,
    LoginAuthLoginPostData,
    LoginAuthLoginPostErrors,
    LoginAuthLoginPostResponses,
    LogoutAuthLogoutPostData,
    LogoutAuthLogoutPostErrors,
    LogoutAuthLogoutPostResponses,
    SetUserSettingsPerformanceUsersUserIdSettingsPostData,
    SetUserSettingsPerformanceUsersUserIdSettingsPostErrors,
    SetUserSettingsPerformanceUsersUserIdSettingsPostResponses,
    UpdateGitlabConfigurationAuthGitlabPostData,
    UpdateGitlabConfigurationAuthGitlabPostErrors,
    UpdateGitlabConfigurationAuthGitlabPostResponses,
} from "./types.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 *
 * Authenticate the sole application user, provisioning if necessary.
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(
    options: Options<LoginAuthLoginPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        LoginAuthLoginPostResponses,
        LoginAuthLoginPostErrors,
        ThrowOnError
    >({
        url: "/auth/login",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Logout
 *
 * Invalidate the currently active session.
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(
    options?: Options<LogoutAuthLogoutPostData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<
        LogoutAuthLogoutPostResponses,
        LogoutAuthLogoutPostErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/logout",
        ...options,
    });
};

/**
 * Update Gitlab Configuration
 *
 * Update the GitLab admin token and store user metadata.
 */
export const updateGitlabConfigurationAuthGitlabPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<UpdateGitlabConfigurationAuthGitlabPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        UpdateGitlabConfigurationAuthGitlabPostResponses,
        UpdateGitlabConfigurationAuthGitlabPostErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/gitlab",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Check Gitlab Token
 *
 * Check the validity of a GitLab token.
 */
export const checkGitlabTokenAuthGitlabTokenCheckPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        CheckGitlabTokenAuthGitlabTokenCheckPostData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).post<
        CheckGitlabTokenAuthGitlabTokenCheckPostResponses,
        CheckGitlabTokenAuthGitlabTokenCheckPostErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/gitlab/token-check",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Get Profile
 *
 * Return the authenticated user's profile information.
 */
export const getProfileAuthMeGet = <ThrowOnError extends boolean = false>(
    options?: Options<GetProfileAuthMeGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetProfileAuthMeGetResponses,
        GetProfileAuthMeGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/me",
        ...options,
    });
};

/**
 * Get Project Members
 *
 * Get members of a GitLab project.
 */
export const getProjectMembersGitlabProjectsProjectIdMembersGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetProjectMembersGitlabProjectsProjectIdMembersGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetProjectMembersGitlabProjectsProjectIdMembersGetResponses,
        GetProjectMembersGitlabProjectsProjectIdMembersGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/gitlab/projects/{project_id}/members",
        ...options,
    });
};

/**
 * List Projects
 *
 * List GitLab projects with optional search filtering.
 */
export const listProjectsGitlabProjectsGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<ListProjectsGitlabProjectsGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        ListProjectsGitlabProjectsGetResponses,
        ListProjectsGitlabProjectsGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/gitlab/projects",
        ...options,
    });
};

/**
 * List GitLab Users
 *
 * Retrieve a list of GitLab users with optional search and pagination.
 */
export const listGitlabUsersUsersGet = <ThrowOnError extends boolean = false>(
    options?: Options<ListGitlabUsersUsersGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        ListGitlabUsersUsersGetResponses,
        ListGitlabUsersUsersGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/users/",
        ...options,
    });
};

/**
 * Get Gitlab User
 *
 * Retrieve a GitLab user by their ID.
 */
export const getGitlabUserUsersUserIdGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetGitlabUserUsersUserIdGetData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetGitlabUserUsersUserIdGetResponses,
        GetGitlabUserUsersUserIdGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/users/{user_id}",
        ...options,
    });
};

/**
 * Get User Timelogs
 *
 * Retrieve user timelogs for a specified period.
 */
export const getUserTimelogsUsersUsernameTimelogsGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<GetUserTimelogsUsersUsernameTimelogsGetData, ThrowOnError>,
) => {
    return (options.client ?? client).get<
        GetUserTimelogsUsersUsernameTimelogsGetResponses,
        GetUserTimelogsUsersUsernameTimelogsGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/users/{username}/timelogs",
        ...options,
    });
};

/**
 * Get User Performance
 *
 * Calculate and retrieve user performance data over a specified time period.
 */
export const getUserPerformancePerformanceUsersUserIdGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetUserPerformancePerformanceUsersUserIdGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetUserPerformancePerformanceUsersUserIdGetResponses,
        GetUserPerformancePerformanceUsersUserIdGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/performance/users/{user_id}",
        ...options,
    });
};

/**
 * Get Project Performance
 *
 * Calculate and retrieve project performance data over a specified time period.
 */
export const getProjectPerformancePerformanceProjectProjectIdUsersUserIdGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetProjectPerformancePerformanceProjectProjectIdUsersUserIdGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetProjectPerformancePerformanceProjectProjectIdUsersUserIdGetResponses,
        GetProjectPerformancePerformanceProjectProjectIdUsersUserIdGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/performance/project/{project_id}/users/{user_id}",
        ...options,
    });
};

/**
 * Get Time Spent Statistics
 *
 * Retrieve time spent statistics for a user over a specified time period.
 */
export const getTimeSpentStatisticsPerformanceusersUserIdTimeSpentGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetTimeSpentStatisticsPerformanceusersUserIdTimeSpentGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetTimeSpentStatisticsPerformanceusersUserIdTimeSpentGetResponses,
        GetTimeSpentStatisticsPerformanceusersUserIdTimeSpentGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/performanceusers/{user_id}/time-spent",
        ...options,
    });
};

/**
 * Get User Settings
 */
export const getUserSettingsPerformanceUsersUserIdSettingsGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetUserSettingsPerformanceUsersUserIdSettingsGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetUserSettingsPerformanceUsersUserIdSettingsGetResponses,
        GetUserSettingsPerformanceUsersUserIdSettingsGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/performance/users/{user_id}/settings",
        ...options,
    });
};

/**
 * Set User Settings
 */
export const setUserSettingsPerformanceUsersUserIdSettingsPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        SetUserSettingsPerformanceUsersUserIdSettingsPostData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).post<
        SetUserSettingsPerformanceUsersUserIdSettingsPostResponses,
        SetUserSettingsPerformanceUsersUserIdSettingsPostErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/performance/users/{user_id}/settings",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Health
 *
 * Simple health check endpoint.
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
    options?: Options<HealthHealthGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        HealthHealthGetResponses,
        unknown,
        ThrowOnError
    >({
        url: "/health",
        ...options,
    });
};
