// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from "./client";
import { client } from "./client.gen";
import type {
    CheckGitlabTokenAuthGitlabTokenCheckPostData,
    CheckGitlabTokenAuthGitlabTokenCheckPostErrors,
    CheckGitlabTokenAuthGitlabTokenCheckPostResponses,
    GetProfileAuthMeGetData,
    GetProfileAuthMeGetErrors,
    GetProfileAuthMeGetResponses,
    GetProjectMembersGitlabProjectsProjectIdMembersGetData,
    GetProjectMembersGitlabProjectsProjectIdMembersGetErrors,
    GetProjectMembersGitlabProjectsProjectIdMembersGetResponses,
    GetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetData,
    GetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetErrors,
    GetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetResponses,
    HealthHealthGetData,
    HealthHealthGetResponses,
    ListProjectsGitlabProjectsGetData,
    ListProjectsGitlabProjectsGetErrors,
    ListProjectsGitlabProjectsGetResponses,
    LoginAuthLoginPostData,
    LoginAuthLoginPostErrors,
    LoginAuthLoginPostResponses,
    LogoutAuthLogoutPostData,
    LogoutAuthLogoutPostResponses,
    RefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostData,
    RefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostErrors,
    RefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostResponses,
    UpdateGitlabConfigurationAuthGitlabPostData,
    UpdateGitlabConfigurationAuthGitlabPostErrors,
    UpdateGitlabConfigurationAuthGitlabPostResponses,
} from "./types.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Login
 *
 * Authenticate the sole application user, provisioning if necessary.
 */
export const loginAuthLoginPost = <ThrowOnError extends boolean = false>(
    options: Options<LoginAuthLoginPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        LoginAuthLoginPostResponses,
        LoginAuthLoginPostErrors,
        ThrowOnError
    >({
        url: "/auth/login",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Logout
 *
 * Invalidate the currently active session.
 */
export const logoutAuthLogoutPost = <ThrowOnError extends boolean = false>(
    options?: Options<LogoutAuthLogoutPostData, ThrowOnError>,
) => {
    return (options?.client ?? client).post<
        LogoutAuthLogoutPostResponses,
        unknown,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/logout",
        ...options,
    });
};

/**
 * Update Gitlab Configuration
 *
 * Update the GitLab admin token and store user metadata.
 */
export const updateGitlabConfigurationAuthGitlabPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<UpdateGitlabConfigurationAuthGitlabPostData, ThrowOnError>,
) => {
    return (options.client ?? client).post<
        UpdateGitlabConfigurationAuthGitlabPostResponses,
        UpdateGitlabConfigurationAuthGitlabPostErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/gitlab",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Check Gitlab Token
 *
 * Check the validity of a GitLab token.
 */
export const checkGitlabTokenAuthGitlabTokenCheckPost = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        CheckGitlabTokenAuthGitlabTokenCheckPostData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).post<
        CheckGitlabTokenAuthGitlabTokenCheckPostResponses,
        CheckGitlabTokenAuthGitlabTokenCheckPostErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/gitlab/token-check",
        ...options,
        headers: {
            "Content-Type": "application/json",
            ...options.headers,
        },
    });
};

/**
 * Get Profile
 *
 * Return the authenticated user's profile information.
 */
export const getProfileAuthMeGet = <ThrowOnError extends boolean = false>(
    options?: Options<GetProfileAuthMeGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        GetProfileAuthMeGetResponses,
        GetProfileAuthMeGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/auth/me",
        ...options,
    });
};

/**
 * Get cached user performance data
 *
 * Return cached performance data if present.
 */
export const getUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGet =
    <ThrowOnError extends boolean = false>(
        options: Options<
            GetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).get<
            GetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetResponses,
            GetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/user-performance/projects/{project_id}/users/{user_id}/performance",
            ...options,
        });
    };

/**
 * Recalculate and update user performance data
 *
 * Recalculate and store fresh performance data.
 */
export const refreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPost =
    <ThrowOnError extends boolean = false>(
        options: Options<
            RefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostData,
            ThrowOnError
        >,
    ) => {
        return (options.client ?? client).post<
            RefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostResponses,
            RefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostErrors,
            ThrowOnError
        >({
            security: [
                {
                    scheme: "bearer",
                    type: "http",
                },
            ],
            url: "/user-performance/projects/{project_id}/users/{user_id}/performance/refresh",
            ...options,
        });
    };

/**
 * Get Project Members
 *
 * Get members of a GitLab project.
 */
export const getProjectMembersGitlabProjectsProjectIdMembersGet = <
    ThrowOnError extends boolean = false,
>(
    options: Options<
        GetProjectMembersGitlabProjectsProjectIdMembersGetData,
        ThrowOnError
    >,
) => {
    return (options.client ?? client).get<
        GetProjectMembersGitlabProjectsProjectIdMembersGetResponses,
        GetProjectMembersGitlabProjectsProjectIdMembersGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/gitlab/projects/{project_id}/members",
        ...options,
    });
};

/**
 * List Projects
 *
 * List GitLab projects with optional search filtering.
 */
export const listProjectsGitlabProjectsGet = <
    ThrowOnError extends boolean = false,
>(
    options?: Options<ListProjectsGitlabProjectsGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        ListProjectsGitlabProjectsGetResponses,
        ListProjectsGitlabProjectsGetErrors,
        ThrowOnError
    >({
        security: [
            {
                scheme: "bearer",
                type: "http",
            },
        ],
        url: "/gitlab/projects",
        ...options,
    });
};

/**
 * Health
 *
 * Simple health check endpoint.
 */
export const healthHealthGet = <ThrowOnError extends boolean = false>(
    options?: Options<HealthHealthGetData, ThrowOnError>,
) => {
    return (options?.client ?? client).get<
        HealthHealthGetResponses,
        unknown,
        ThrowOnError
    >({
        url: "/health",
        ...options,
    });
};
