// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Commits
 *
 * Details of a Commit.
 */
export type Commits = {
    /**
     * Title
     */
    title: string;
    /**
     * Message
     */
    message: string;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Authored Date
     */
    authored_date: string;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
};

/**
 * ErrorResponseModel
 *
 * Standard error response model.
 */
export type ErrorResponseModel = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * GitLabConfigRequest
 *
 * Payload for configuring the GitLab admin token and URL.
 */
export type GitLabConfigRequest = {
    /**
     * Gitlab Url
     */
    gitlab_url: string;
    /**
     * Gitlab Admin Token
     */
    gitlab_admin_token: string;
};

/**
 * GitLabConfigResponse
 *
 * Response after updating the GitLab configuration.
 */
export type GitLabConfigResponse = {
    /**
     * Gitlab User Info
     */
    gitlab_user_info: {
        [key: string]: unknown;
    };
    /**
     * Gitlab Url
     */
    gitlab_url: string;
};

/**
 * GitLabUser
 */
export type GitLabUser = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Public Email
     */
    public_email: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * State
     */
    state: string;
    /**
     * Locked
     */
    locked: boolean;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Bot
     */
    bot: boolean;
    /**
     * Last Sign In At
     */
    last_sign_in_at: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * GitlabTokenCheckResponse
 *
 * Response for GitLab token validation check.
 */
export type GitlabTokenCheckResponse = {
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Gitlab User Info
     */
    gitlab_user_info?: {
        [key: string]: unknown;
    } | null;
};

/**
 * GitlabUserInfo
 *
 * Represents GitLab user information.
 */
export type GitlabUserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * IssueInfo
 */
export type IssueInfo = {
    /**
     * Iid
     */
    iid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * State
     */
    state: string;
    /**
     * Reference
     */
    reference: string;
};

/**
 * LoginRequest
 *
 * Incoming payload for user login or first-time bootstrap.
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Gitlab Url
     */
    gitlab_url?: string | null;
    /**
     * Gitlab Admin Token
     */
    gitlab_admin_token?: string | null;
};

/**
 * LoginResponse
 *
 * Token response returned after successful authentication.
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Username
     */
    username: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Gitlab Configured
     */
    gitlab_configured: boolean;
    /**
     * Gitlab User Info
     */
    gitlab_user_info?: {
        [key: string]: unknown;
    } | null;
};

/**
 * LogoutResponse
 *
 * Acknowledgement returned after logout.
 */
export type LogoutResponse = {
    /**
     * Success
     */
    success?: boolean;
};

/**
 * MembersResponse
 *
 * Response schema for GitLab project members.
 */
export type MembersResponse = {
    /**
     * Id
     *
     * User ID
     */
    id: number;
    /**
     * Username
     *
     * Username
     */
    username: string;
    /**
     * Name
     *
     * Full name
     */
    name: string;
    /**
     * Web Url
     *
     * Web URL to the user's profile
     */
    web_url: string;
    /**
     * Avatar Url
     *
     * URL to the user's avatar
     */
    avatar_url?: string | null;
    /**
     * State
     *
     * Account state
     */
    state: string;
    /**
     * Access Level
     *
     * Access level in the project
     */
    access_level: number;
    /**
     * Access Level Name
     *
     * Access level name
     */
    access_level_name: string;
};

/**
 * MergeRequestInfo
 */
export type MergeRequestInfo = {
    /**
     * Iid
     */
    iid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * State
     */
    state: string;
    /**
     * Reference
     */
    reference: string;
};

/**
 * MrDetails
 *
 * Details of a Merge Request.
 */
export type MrDetails = {
    /**
     * Iid
     */
    iid: number;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * State
     */
    state: string;
    /**
     * Commits Count
     */
    commits_count: number;
    /**
     * Commits
     */
    commits: Array<Commits>;
};

/**
 * NoteInfo
 */
export type NoteInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Body
     */
    body: string;
};

/**
 * PageInfo
 */
export type PageInfo = {
    /**
     * Hasnextpage
     */
    hasNextPage: boolean;
    /**
     * Haspreviouspage
     */
    hasPreviousPage: boolean;
    /**
     * Startcursor
     */
    startCursor?: string | null;
    /**
     * Endcursor
     */
    endCursor?: string | null;
};

/**
 * ProjectInfo
 */
export type ProjectInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * Fullpath
     */
    fullPath: string;
    /**
     * Namewithnamespace
     */
    nameWithNamespace: string;
};

/**
 * ProjectsResponse
 *
 * Response schema for GitLab projects.
 */
export type ProjectsResponse = {
    /**
     * Id
     *
     * Project ID
     */
    id: number;
    /**
     * Name
     *
     * Project name
     */
    name: string;
    /**
     * Name With Namespace
     *
     * Project name with namespace
     */
    name_with_namespace: string;
    /**
     * Path With Namespace
     *
     * Project path with namespace
     */
    path_with_namespace: string;
    /**
     * Tag List
     *
     * List of project tags
     */
    tag_list: Array<string>;
    /**
     * Topics
     *
     * List of project topics
     */
    topics: Array<string>;
    /**
     * Web Url
     *
     * Web URL to the project
     */
    web_url: string;
    /**
     * Avatar Url
     *
     * URL to the project's avatar
     */
    avatar_url?: string | null;
    /**
     * Created At
     *
     * Project creation timestamp
     */
    created_at: string;
};

/**
 * TimelogData
 */
export type TimelogData = {
    /**
     * Count
     */
    count: number;
    /**
     * Totalspenttime
     */
    totalSpentTime: string;
    /**
     * Nodes
     */
    nodes: Array<TimelogNode>;
    pageInfo: PageInfo;
};

/**
 * TimelogNode
 */
export type TimelogNode = {
    /**
     * Id
     */
    id: number;
    project: ProjectInfo;
    /**
     * Timespent
     */
    timeSpent: number;
    user: UserInfo;
    /**
     * Spentat
     */
    spentAt: string;
    note?: NoteInfo | null;
    /**
     * Summary
     */
    summary?: string | null;
    issue?: IssueInfo | null;
    mergeRequest?: MergeRequestInfo | null;
};

/**
 * UserInfo
 */
export type UserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Avatarurl
     */
    avatarUrl?: string | null;
    /**
     * Webpath
     */
    webPath?: string | null;
};

/**
 * UserPerformanceResponse
 *
 * Response model for user performance data.
 */
export type UserPerformanceResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Project Path Name
     */
    project_path_name: string;
    /**
     * Since
     */
    since: string;
    /**
     * Until
     */
    until: string;
    /**
     * Total Commits
     */
    total_commits: number;
    /**
     * Total Additions
     */
    total_additions: number;
    /**
     * Total Deletions
     */
    total_deletions: number;
    /**
     * Total Changes
     */
    total_changes: number;
    /**
     * Total Mr Contributed
     */
    total_mr_contributed: number;
    /**
     * Daily Commit Counts
     */
    daily_commit_counts: {
        [key: string]: number;
    };
    /**
     * Daily Additions
     */
    daily_additions: {
        [key: string]: number;
    };
    /**
     * Daily Deletions
     */
    daily_deletions: {
        [key: string]: number;
    };
    /**
     * Daily Changes
     */
    daily_changes: {
        [key: string]: number;
    };
    /**
     * Merge Requests
     */
    merge_requests: Array<MrDetails>;
    /**
     * Llm Prompt Suggestion
     */
    llm_prompt_suggestion: string;
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Calculated At
     */
    calculated_at: string;
};

/**
 * UserProfileResponse
 *
 * Basic profile snapshot for the single configured user.
 */
export type UserProfileResponse = {
    /**
     * Username
     */
    username: string;
    gitlab_user_info?: GitlabUserInfo | null;
    /**
     * Gitlab Url
     */
    gitlab_url?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginAuthLoginPostData = {
    body: LoginRequest;
    headers?: {
        /**
         * User-Agent
         */
        "User-Agent"?: string | null;
    };
    path?: never;
    query?: never;
    url: "/auth/login";
};

export type LoginAuthLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError =
    LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginAuthLoginPostResponse =
    LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type LogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/auth/logout";
};

export type LogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: LogoutResponse;
};

export type LogoutAuthLogoutPostResponse =
    LogoutAuthLogoutPostResponses[keyof LogoutAuthLogoutPostResponses];

export type UpdateGitlabConfigurationAuthGitlabPostData = {
    body: GitLabConfigRequest;
    path?: never;
    query?: never;
    url: "/auth/gitlab";
};

export type UpdateGitlabConfigurationAuthGitlabPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateGitlabConfigurationAuthGitlabPostError =
    UpdateGitlabConfigurationAuthGitlabPostErrors[keyof UpdateGitlabConfigurationAuthGitlabPostErrors];

export type UpdateGitlabConfigurationAuthGitlabPostResponses = {
    /**
     * Successful Response
     */
    200: GitLabConfigResponse;
};

export type UpdateGitlabConfigurationAuthGitlabPostResponse =
    UpdateGitlabConfigurationAuthGitlabPostResponses[keyof UpdateGitlabConfigurationAuthGitlabPostResponses];

export type CheckGitlabTokenAuthGitlabTokenCheckPostData = {
    body: GitLabConfigRequest;
    path?: never;
    query?: never;
    url: "/auth/gitlab/token-check";
};

export type CheckGitlabTokenAuthGitlabTokenCheckPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CheckGitlabTokenAuthGitlabTokenCheckPostError =
    CheckGitlabTokenAuthGitlabTokenCheckPostErrors[keyof CheckGitlabTokenAuthGitlabTokenCheckPostErrors];

export type CheckGitlabTokenAuthGitlabTokenCheckPostResponses = {
    /**
     * Successful Response
     */
    200: GitlabTokenCheckResponse;
};

export type CheckGitlabTokenAuthGitlabTokenCheckPostResponse =
    CheckGitlabTokenAuthGitlabTokenCheckPostResponses[keyof CheckGitlabTokenAuthGitlabTokenCheckPostResponses];

export type GetProfileAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/auth/me";
};

export type GetProfileAuthMeGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
};

export type GetProfileAuthMeGetError =
    GetProfileAuthMeGetErrors[keyof GetProfileAuthMeGetErrors];

export type GetProfileAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetProfileAuthMeGetResponse =
    GetProfileAuthMeGetResponses[keyof GetProfileAuthMeGetResponses];

export type GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetData =
    {
        body?: never;
        path: {
            /**
             * User Id
             *
             * GitLab user ID
             */
            user_id: number;
            /**
             * Project Id
             *
             * GitLab project ID or path
             */
            project_id: string;
        };
        query: {
            /**
             * Start Date
             *
             * Start date
             */
            start_date: string;
            /**
             * End Date
             *
             * End date
             */
            end_date: string;
        };
        url: "/project-user-performance/projects/{project_id}/users/{user_id}/performance";
    };

export type GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetErrors =
    {
        /**
         * Invalid credentials
         */
        401: ErrorResponseModel;
        /**
         * Resource not found
         */
        404: ErrorResponseModel;
        /**
         * Validation Error
         */
        422: HttpValidationError;
    };

export type GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetError =
    GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetErrors[keyof GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetErrors];

export type GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetResponses =
    {
        /**
         * Successful Response
         */
        200: UserPerformanceResponse;
    };

export type GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetResponse =
    GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetResponses[keyof GetUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetResponses];

export type RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostData =
    {
        body?: never;
        path: {
            /**
             * User Id
             *
             * GitLab user ID
             */
            user_id: number;
            /**
             * Project Id
             *
             * GitLab project ID or path
             */
            project_id: string;
        };
        query: {
            /**
             * Start Date
             *
             * Start date
             */
            start_date: string;
            /**
             * End Date
             *
             * End date
             */
            end_date: string;
        };
        url: "/project-user-performance/projects/{project_id}/users/{user_id}/performance/refresh";
    };

export type RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostErrors =
    {
        /**
         * Invalid credentials
         */
        401: ErrorResponseModel;
        /**
         * Validation Error
         */
        422: HttpValidationError;
        /**
         * Internal Server Error
         */
        500: ErrorResponseModel;
    };

export type RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostError =
    RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostErrors[keyof RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostErrors];

export type RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostResponses =
    {
        /**
         * Successful Response
         */
        200: UserPerformanceResponse;
    };

export type RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostResponse =
    RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostResponses[keyof RefreshUserPerformanceProjectUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostResponses];

export type GetProjectMembersGitlabProjectsProjectIdMembersGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * GitLab project ID
         */
        project_id: number;
    };
    query?: {
        /**
         * Page
         *
         * Page number for pagination
         */
        page?: number;
        /**
         * Per Page
         *
         * Number of members per page
         */
        per_page?: number;
        /**
         * Search
         *
         * Filter members by username or name
         */
        search?: string | null;
    };
    url: "/gitlab/projects/{project_id}/members";
};

export type GetProjectMembersGitlabProjectsProjectIdMembersGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProjectMembersGitlabProjectsProjectIdMembersGetError =
    GetProjectMembersGitlabProjectsProjectIdMembersGetErrors[keyof GetProjectMembersGitlabProjectsProjectIdMembersGetErrors];

export type GetProjectMembersGitlabProjectsProjectIdMembersGetResponses = {
    /**
     * Response Get Project Members Gitlab Projects  Project Id  Members Get
     *
     * Successful Response
     */
    200: Array<MembersResponse>;
};

export type GetProjectMembersGitlabProjectsProjectIdMembersGetResponse =
    GetProjectMembersGitlabProjectsProjectIdMembersGetResponses[keyof GetProjectMembersGitlabProjectsProjectIdMembersGetResponses];

export type ListProjectsGitlabProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * Page number for pagination
         */
        page?: number;
        /**
         * Per Page
         *
         * Number of projects per page
         */
        per_page?: number;
        /**
         * Search
         *
         * Filter projects by name or path
         */
        search?: string | null;
        /**
         * Membership
         *
         * Only return projects the authenticated user is a member of
         */
        membership?: boolean | null;
    };
    url: "/gitlab/projects";
};

export type ListProjectsGitlabProjectsGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListProjectsGitlabProjectsGetError =
    ListProjectsGitlabProjectsGetErrors[keyof ListProjectsGitlabProjectsGetErrors];

export type ListProjectsGitlabProjectsGetResponses = {
    /**
     * Response List Projects Gitlab Projects Get
     *
     * Successful Response
     */
    200: Array<ProjectsResponse>;
};

export type ListProjectsGitlabProjectsGetResponse =
    ListProjectsGitlabProjectsGetResponses[keyof ListProjectsGitlabProjectsGetResponses];

export type ListGitlabUsersUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * Page number for pagination.
         */
        page?: number;
        /**
         * Per Page
         *
         * Number of users per page.
         */
        per_page?: number;
        /**
         * Humans
         *
         * Whether to include only human users.
         */
        humans?: boolean;
        /**
         * Search
         *
         * Search term to filter users by username or name.
         */
        search?: string | null;
    };
    url: "/users/";
};

export type ListGitlabUsersUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListGitlabUsersUsersGetError =
    ListGitlabUsersUsersGetErrors[keyof ListGitlabUsersUsersGetErrors];

export type ListGitlabUsersUsersGetResponses = {
    /**
     * Response List Gitlab Users Users  Get
     *
     * Successful Response
     */
    200: Array<GitLabUser>;
};

export type ListGitlabUsersUsersGetResponse =
    ListGitlabUsersUsersGetResponses[keyof ListGitlabUsersUsersGetResponses];

export type GetGitlabUserUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the GitLab user to retrieve.
         */
        user_id: number;
    };
    query?: never;
    url: "/users/{user_id}";
};

export type GetGitlabUserUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetGitlabUserUsersUserIdGetError =
    GetGitlabUserUsersUserIdGetErrors[keyof GetGitlabUserUsersUserIdGetErrors];

export type GetGitlabUserUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: GitLabUser;
};

export type GetGitlabUserUsersUserIdGetResponse =
    GetGitlabUserUsersUserIdGetResponses[keyof GetGitlabUserUsersUserIdGetResponses];

export type GetUserTimelogsUsersUsernameTimelogsGetData = {
    body?: never;
    path: {
        /**
         * Username
         *
         * The username of the user to retrieve timelogs for.
         */
        username: string;
    };
    query: {
        /**
         * Start Time
         *
         * The start date for the timelog period.
         */
        start_time: string;
        /**
         * End Time
         *
         * The end date for the timelog period.
         */
        end_time: string;
        /**
         * First
         *
         * Number of timelogs to retrieve per page.
         */
        first?: number;
        /**
         * After
         *
         * Cursor for pagination to fetch the next set of timelogs.
         */
        after?: string | null;
    };
    url: "/users/{username}/timelogs";
};

export type GetUserTimelogsUsersUsernameTimelogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetUserTimelogsUsersUsernameTimelogsGetError =
    GetUserTimelogsUsersUsernameTimelogsGetErrors[keyof GetUserTimelogsUsersUsernameTimelogsGetErrors];

export type GetUserTimelogsUsersUsernameTimelogsGetResponses = {
    /**
     * Successful Response
     */
    200: TimelogData;
};

export type GetUserTimelogsUsersUsernameTimelogsGetResponse =
    GetUserTimelogsUsersUsernameTimelogsGetResponses[keyof GetUserTimelogsUsersUsernameTimelogsGetResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/health";
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse =
    HealthHealthGetResponses[keyof HealthHealthGetResponses];
