// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * CommitInfo
 *
 * Single commit details.
 */
export type CommitInfo = {
    /**
     * Title
     */
    title: string;
    /**
     * Message
     */
    message: string;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Authored Date
     */
    authored_date: string;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
};

/**
 * ErrorResponseModel
 *
 * Standard error response model.
 */
export type ErrorResponseModel = {
    /**
     * Detail
     */
    detail: string;
};

/**
 * GeneralProjectPerformance
 *
 * Top-level structure returned by the performance service for a project.
 */
export type GeneralProjectPerformance = {
    /**
     * Project Id
     */
    project_id: number;
    /**
     * Project Name
     */
    project_name: string;
    /**
     * Commits
     */
    commits: number;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
    /**
     * Changes
     */
    changes: number;
    /**
     * Contributors
     */
    contributors: Array<ProjectContributorStats>;
    /**
     * Daily Commit Counts
     */
    daily_commit_counts: {
        [key: string]: number;
    };
    /**
     * Daily Additions
     */
    daily_additions: {
        [key: string]: number;
    };
    /**
     * Daily Deletions
     */
    daily_deletions: {
        [key: string]: number;
    };
    /**
     * Daily Changes
     */
    daily_changes: {
        [key: string]: number;
    };
};

/**
 * GeneralUserPerformance
 *
 * Top-level structure returned by the performance service.
 */
export type GeneralUserPerformance = {
    /**
     * Userd Id
     */
    userd_id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Commits
     */
    commits: number;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
    /**
     * Changes
     */
    changes: number;
    /**
     * Mr Contributed
     */
    mr_contributed: number;
    /**
     * Approvals Given
     */
    approvals_given: number;
    /**
     * Review Merge Requests
     */
    review_merge_requests: number;
    /**
     * Review Comments
     */
    review_comments: number;
    /**
     * Notes Authored
     */
    notes_authored: number;
    /**
     * Daily Commit Counts
     */
    daily_commit_counts: {
        [key: string]: number;
    };
    /**
     * Daily Additions
     */
    daily_additions: {
        [key: string]: number;
    };
    /**
     * Daily Deletions
     */
    daily_deletions: {
        [key: string]: number;
    };
    /**
     * Daily Changes
     */
    daily_changes: {
        [key: string]: number;
    };
    /**
     * Project Performances
     */
    project_performances: Array<ProjectPerformanceShort>;
};

/**
 * GitLabConfigRequest
 *
 * Payload for configuring the GitLab admin token and URL.
 */
export type GitLabConfigRequest = {
    /**
     * Gitlab Url
     */
    gitlab_url: string;
    /**
     * Gitlab Admin Token
     */
    gitlab_admin_token: string;
};

/**
 * GitLabConfigResponse
 *
 * Response after updating the GitLab configuration.
 */
export type GitLabConfigResponse = {
    /**
     * Gitlab User Info
     */
    gitlab_user_info: {
        [key: string]: unknown;
    };
    /**
     * Gitlab Url
     */
    gitlab_url: string;
};

/**
 * GitLabUser
 */
export type GitLabUser = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Public Email
     */
    public_email: string | null;
    /**
     * Name
     */
    name: string;
    /**
     * State
     */
    state: string;
    /**
     * Locked
     */
    locked: boolean;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Bot
     */
    bot: boolean;
    /**
     * Last Sign In At
     */
    last_sign_in_at: string | null;
    /**
     * Email
     */
    email: string | null;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * GitlabTokenCheckResponse
 *
 * Response for GitLab token validation check.
 */
export type GitlabTokenCheckResponse = {
    /**
     * Valid
     */
    valid: boolean;
    /**
     * Gitlab User Info
     */
    gitlab_user_info?: {
        [key: string]: unknown;
    } | null;
};

/**
 * GitlabUserInfo
 *
 * Represents GitLab user information.
 */
export type GitlabUserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Name
     */
    name: string;
    /**
     * Email
     */
    email: string | null;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Avatar Url
     */
    avatar_url: string | null;
    /**
     * State
     */
    state: string;
    /**
     * Is Admin
     */
    is_admin: boolean;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LoginRequest
 *
 * Incoming payload for user login or first-time bootstrap.
 */
export type LoginRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Gitlab Url
     */
    gitlab_url?: string | null;
    /**
     * Gitlab Admin Token
     */
    gitlab_admin_token?: string | null;
};

/**
 * LoginResponse
 *
 * Token response returned after successful authentication.
 */
export type LoginResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
    /**
     * Username
     */
    username: string;
    /**
     * Expires At
     */
    expires_at: string;
    /**
     * Gitlab Configured
     */
    gitlab_configured: boolean;
    /**
     * Gitlab User Info
     */
    gitlab_user_info?: {
        [key: string]: unknown;
    } | null;
};

/**
 * LogoutResponse
 *
 * Acknowledgement returned after logout.
 */
export type LogoutResponse = {
    /**
     * Success
     */
    success?: boolean;
};

/**
 * MembersResponse
 *
 * Response schema for GitLab project members.
 */
export type MembersResponse = {
    /**
     * Id
     *
     * User ID
     */
    id: number;
    /**
     * Username
     *
     * Username
     */
    username: string;
    /**
     * Name
     *
     * Full name
     */
    name: string;
    /**
     * Web Url
     *
     * Web URL to the user's profile
     */
    web_url: string;
    /**
     * Avatar Url
     *
     * URL to the user's avatar
     */
    avatar_url?: string | null;
    /**
     * State
     *
     * Account state
     */
    state: string;
    /**
     * Access Level
     *
     * Access level in the project
     */
    access_level: number;
    /**
     * Access Level Name
     *
     * Access level name
     */
    access_level_name: string;
};

/**
 * MergeRequestDetails
 *
 * Detailed information about a merge request and its commits.
 */
export type MergeRequestDetails = {
    /**
     * Iid
     */
    iid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * State
     */
    state: string;
    /**
     * Reference
     */
    reference: string;
    /**
     * Description
     */
    description: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Total Commits
     */
    total_commits: number;
    /**
     * Total Additions
     */
    total_additions: number;
    /**
     * Total Deletions
     */
    total_deletions: number;
    /**
     * Commits Count
     */
    commits_count: number;
    /**
     * Commits
     */
    commits?: Array<CommitInfo> | null;
};

/**
 * NoteInfo
 */
export type NoteInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Body
     */
    body: string;
};

/**
 * PageInfo
 */
export type PageInfo = {
    /**
     * Hasnextpage
     */
    hasNextPage: boolean;
    /**
     * Haspreviouspage
     */
    hasPreviousPage: boolean;
    /**
     * Startcursor
     */
    startCursor?: string | null;
    /**
     * Endcursor
     */
    endCursor?: string | null;
};

/**
 * ProjectContributorStats
 *
 * Contributor-specific stats within a project. (authors of commits)
 */
export type ProjectContributorStats = {
    /**
     * Author Name
     */
    author_name: string;
    /**
     * Author Email
     */
    author_email: string;
    /**
     * Commits
     */
    commits: number;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
    /**
     * Changes
     */
    changes: number;
};

/**
 * ProjectPerformanceResponse
 *
 * Project-scoped performance metrics for a user.
 */
export type ProjectPerformanceResponse = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Path With Namespace
     */
    path_with_namespace: string;
    /**
     * Name With Namespace
     */
    name_with_namespace: string;
    /**
     * Since
     */
    since: string;
    /**
     * Until
     */
    until: string;
    /**
     * Commits
     */
    commits: number;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
    /**
     * Changes
     */
    changes: number;
    /**
     * Mr Contributed
     */
    mr_contributed: number;
    /**
     * Calculated At
     */
    calculated_at: string;
    /**
     * Merge Requests
     */
    merge_requests?: Array<MergeRequestDetails> | null;
    /**
     * Daily Commit Counts
     */
    daily_commit_counts: {
        [key: string]: number;
    };
    /**
     * Daily Additions
     */
    daily_additions: {
        [key: string]: number;
    };
    /**
     * Daily Deletions
     */
    daily_deletions: {
        [key: string]: number;
    };
    /**
     * Daily Changes
     */
    daily_changes: {
        [key: string]: number;
    };
};

/**
 * ProjectPerformanceShort
 *
 * Short summary of project-scoped performance metrics for a user.
 */
export type ProjectPerformanceShort = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Path With Namespace
     */
    path_with_namespace: string;
    /**
     * Name With Namespace
     */
    name_with_namespace: string;
    /**
     * Since
     */
    since: string;
    /**
     * Until
     */
    until: string;
    /**
     * Commits
     */
    commits: number;
    /**
     * Additions
     */
    additions: number;
    /**
     * Deletions
     */
    deletions: number;
    /**
     * Changes
     */
    changes: number;
    /**
     * Mr Contributed
     */
    mr_contributed: number;
    /**
     * Calculated At
     */
    calculated_at: string;
    /**
     * Merge Requests
     */
    merge_requests?: Array<MergeRequestDetails> | null;
};

/**
 * ProjectTimelogs
 *
 * Timelog aggregation for a single project.
 */
export type ProjectTimelogs = {
    project: AppSchemasPerformanceProjectInfo;
    /**
     * Timelogs
     */
    timelogs: Array<AppSchemasPerformanceTimelogNode>;
    /**
     * Total Time Spent Hours
     */
    total_time_spent_hours: number;
};

/**
 * ProjectsResponse
 *
 * Response schema for GitLab projects.
 */
export type ProjectsResponse = {
    /**
     * Id
     *
     * Project ID
     */
    id: number;
    /**
     * Name
     *
     * Project name
     */
    name: string;
    /**
     * Name With Namespace
     *
     * Project name with namespace
     */
    name_with_namespace: string;
    /**
     * Path With Namespace
     *
     * Project path with namespace
     */
    path_with_namespace: string;
    /**
     * Tag List
     *
     * List of project tags
     */
    tag_list: Array<string>;
    /**
     * Topics
     *
     * List of project topics
     */
    topics: Array<string>;
    /**
     * Web Url
     *
     * Web URL to the project
     */
    web_url: string;
    /**
     * Avatar Url
     *
     * URL to the project's avatar
     */
    avatar_url?: string | null;
    /**
     * Created At
     *
     * Project creation timestamp
     */
    created_at: string;
};

/**
 * ScheduledReportCreate
 *
 * Payload for creating a new schedule.
 */
export type ScheduledReportCreate = {
    /**
     * User Id
     *
     * GitLab user ID to generate the report for.
     */
    user_id: number;
    /**
     * To
     *
     * Primary recipient list for the report email.
     */
    to: Array<string>;
    /**
     * Cc
     *
     * Optional CC recipients for the report email.
     */
    cc?: Array<string>;
    /**
     * Bcc
     *
     * Optional BCC recipients for the report email.
     */
    bcc?: Array<string>;
    /**
     * Subject
     *
     * Optional subject override. Defaults to a generated subject.
     */
    subject?: string | null;
    /**
     * Day Of Week
     *
     * APScheduler day-of-week value (mon-sun or 0-6). Uses UTC.
     */
    day_of_week?: string;
    /**
     * Hour Utc
     *
     * Hour of the day (UTC) to send the report.
     */
    hour_utc?: number;
    /**
     * Minute Utc
     *
     * Minute of the hour (UTC) to send the report.
     */
    minute_utc?: number;
    /**
     * Active
     *
     * Whether the schedule is enabled. Disabled schedules do not run.
     */
    active?: boolean;
};

/**
 * ScheduledReportResponse
 *
 * Response model describing a scheduled report.
 */
export type ScheduledReportResponse = {
    /**
     * User Id
     *
     * GitLab user ID to generate the report for.
     */
    user_id: number;
    /**
     * To
     *
     * Primary recipient list for the report email.
     */
    to: Array<string>;
    /**
     * Cc
     *
     * Optional CC recipients for the report email.
     */
    cc?: Array<string>;
    /**
     * Bcc
     *
     * Optional BCC recipients for the report email.
     */
    bcc?: Array<string>;
    /**
     * Subject
     *
     * Optional subject override. Defaults to a generated subject.
     */
    subject?: string | null;
    /**
     * Day Of Week
     *
     * APScheduler day-of-week value (mon-sun or 0-6). Uses UTC.
     */
    day_of_week?: string;
    /**
     * Hour Utc
     *
     * Hour of the day (UTC) to send the report.
     */
    hour_utc?: number;
    /**
     * Minute Utc
     *
     * Minute of the hour (UTC) to send the report.
     */
    minute_utc?: number;
    /**
     * Active
     *
     * Whether the schedule is enabled. Disabled schedules do not run.
     */
    active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Last Sent At
     */
    last_sent_at?: string | null;
    /**
     * Last Error
     */
    last_error?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Next Run At
     *
     * Next planned runtime for this schedule (UTC).
     */
    next_run_at?: string | null;
};

/**
 * ScheduledReportUpdate
 *
 * Payload for updating an existing schedule.
 */
export type ScheduledReportUpdate = {
    /**
     * To
     */
    to?: Array<string> | null;
    /**
     * Cc
     */
    cc?: Array<string> | null;
    /**
     * Bcc
     */
    bcc?: Array<string> | null;
    /**
     * Subject
     */
    subject?: string | null;
    /**
     * Day Of Week
     */
    day_of_week?: string | number | null;
    /**
     * Hour Utc
     *
     * Hour of the day (UTC) to send the report.
     */
    hour_utc?: number | null;
    /**
     * Minute Utc
     *
     * Minute of the hour (UTC) to send the report.
     */
    minute_utc?: number | null;
    /**
     * Active
     */
    active?: boolean | null;
};

/**
 * TimeSpentStats
 *
 * Time-spent related activity such as logged time per day and per project.
 */
export type TimeSpentStats = {
    /**
     * User Id
     */
    user_id: number;
    /**
     * Username
     */
    username: string;
    /**
     * Daily Project Time Spent
     */
    daily_project_time_spent: Array<[string, string, number]>;
    /**
     * Total Time Spent Hours
     */
    total_time_spent_hours: number;
    /**
     * Mr Contributed
     */
    mr_contributed: number;
    /**
     * Issue Contributed
     */
    issue_contributed: number;
    /**
     * Project Timelogs
     */
    project_timelogs: Array<ProjectTimelogs>;
};

/**
 * TimelogData
 */
export type TimelogData = {
    /**
     * Count
     */
    count: number;
    /**
     * Totalspenttime
     */
    totalSpentTime: string;
    /**
     * Nodes
     */
    nodes: Array<AppSchemasUsersTimelogNode>;
    pageInfo: PageInfo;
};

/**
 * UserInfo
 */
export type UserInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Username
     */
    username: string;
    /**
     * Avatarurl
     */
    avatarUrl?: string | null;
    /**
     * Webpath
     */
    webPath?: string | null;
};

/**
 * UserPerfomanceSettingsRequest
 */
export type UserPerfomanceSettingsRequest = {
    /**
     * Additional User Emails
     */
    additional_user_emails?: Array<string>;
};

/**
 * UserPerformanceSettings
 */
export type UserPerformanceSettings = {
    /**
     * Additional User Emails
     */
    additional_user_emails?: Array<string>;
    /**
     * User Id
     */
    user_id: number;
};

/**
 * UserProfileResponse
 *
 * Basic profile snapshot for the single configured user.
 */
export type UserProfileResponse = {
    /**
     * Username
     */
    username: string;
    gitlab_user_info?: GitlabUserInfo | null;
    /**
     * Gitlab Url
     */
    gitlab_url?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * IssueInfo
 *
 * Minimal issue reference used in timelog entries.
 */
export type AppSchemasPerformanceIssueInfo = {
    /**
     * Iid
     */
    iid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * State
     */
    state: string;
    /**
     * Reference
     */
    reference: string;
};

/**
 * MergeRequestInfo
 *
 * Minimal merge request reference used in timelog entries.
 */
export type AppSchemasPerformanceMergeRequestInfo = {
    /**
     * Iid
     */
    iid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * State
     */
    state: string;
    /**
     * Reference
     */
    reference: string;
};

/**
 * ProjectInfo
 *
 * Basic information about a GitLab project.
 */
export type AppSchemasPerformanceProjectInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Name
     */
    name: string;
    /**
     * Avatar Url
     */
    avatar_url?: string | null;
    /**
     * Web Url
     */
    web_url: string;
    /**
     * Path With Namespace
     */
    path_with_namespace: string;
    /**
     * Name With Namespace
     */
    name_with_namespace: string;
};

/**
 * TimelogNode
 *
 * Single timelog entry for a project/issue/MR.
 */
export type AppSchemasPerformanceTimelogNode = {
    /**
     * Id
     */
    id: number;
    project: AppSchemasPerformanceProjectInfo;
    /**
     * Time Spent
     */
    time_spent: number;
    /**
     * Spent At
     */
    spent_at: string;
    /**
     * Summary
     */
    summary?: string | null;
    issue?: AppSchemasPerformanceIssueInfo | null;
    merge_request?: AppSchemasPerformanceMergeRequestInfo | null;
};

/**
 * IssueInfo
 */
export type AppSchemasUsersIssueInfo = {
    /**
     * Iid
     */
    iid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * State
     */
    state: string;
    /**
     * Reference
     */
    reference: string;
};

/**
 * MergeRequestInfo
 */
export type AppSchemasUsersMergeRequestInfo = {
    /**
     * Iid
     */
    iid: string;
    /**
     * Title
     */
    title: string;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * State
     */
    state: string;
    /**
     * Reference
     */
    reference: string;
};

/**
 * ProjectInfo
 */
export type AppSchemasUsersProjectInfo = {
    /**
     * Id
     */
    id: number;
    /**
     * Weburl
     */
    webUrl: string;
    /**
     * Fullpath
     */
    fullPath: string;
    /**
     * Namewithnamespace
     */
    nameWithNamespace: string;
};

/**
 * TimelogNode
 */
export type AppSchemasUsersTimelogNode = {
    /**
     * Id
     */
    id: number;
    project: AppSchemasUsersProjectInfo;
    /**
     * Timespent
     */
    timeSpent: number;
    user: UserInfo;
    /**
     * Spentat
     */
    spentAt: string;
    note?: NoteInfo | null;
    /**
     * Summary
     */
    summary?: string | null;
    issue?: AppSchemasUsersIssueInfo | null;
    mergeRequest?: AppSchemasUsersMergeRequestInfo | null;
};

export type LoginApiAuthLoginPostData = {
    body: LoginRequest;
    headers?: {
        /**
         * User-Agent
         */
        "User-Agent"?: string | null;
    };
    path?: never;
    query?: never;
    url: "/api/auth/login";
};

export type LoginApiAuthLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type LoginApiAuthLoginPostError =
    LoginApiAuthLoginPostErrors[keyof LoginApiAuthLoginPostErrors];

export type LoginApiAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: LoginResponse;
};

export type LoginApiAuthLoginPostResponse =
    LoginApiAuthLoginPostResponses[keyof LoginApiAuthLoginPostResponses];

export type LogoutApiAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/auth/logout";
};

export type LogoutApiAuthLogoutPostErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type LogoutApiAuthLogoutPostError =
    LogoutApiAuthLogoutPostErrors[keyof LogoutApiAuthLogoutPostErrors];

export type LogoutApiAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: LogoutResponse;
};

export type LogoutApiAuthLogoutPostResponse =
    LogoutApiAuthLogoutPostResponses[keyof LogoutApiAuthLogoutPostResponses];

export type UpdateGitlabConfigurationApiAuthGitlabPostData = {
    body: GitLabConfigRequest;
    path?: never;
    query?: never;
    url: "/api/auth/gitlab";
};

export type UpdateGitlabConfigurationApiAuthGitlabPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type UpdateGitlabConfigurationApiAuthGitlabPostError =
    UpdateGitlabConfigurationApiAuthGitlabPostErrors[keyof UpdateGitlabConfigurationApiAuthGitlabPostErrors];

export type UpdateGitlabConfigurationApiAuthGitlabPostResponses = {
    /**
     * Successful Response
     */
    200: GitLabConfigResponse;
};

export type UpdateGitlabConfigurationApiAuthGitlabPostResponse =
    UpdateGitlabConfigurationApiAuthGitlabPostResponses[keyof UpdateGitlabConfigurationApiAuthGitlabPostResponses];

export type CheckGitlabTokenApiAuthGitlabTokenCheckPostData = {
    body: GitLabConfigRequest;
    path?: never;
    query?: never;
    url: "/api/auth/gitlab/token-check";
};

export type CheckGitlabTokenApiAuthGitlabTokenCheckPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorResponseModel;
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type CheckGitlabTokenApiAuthGitlabTokenCheckPostError =
    CheckGitlabTokenApiAuthGitlabTokenCheckPostErrors[keyof CheckGitlabTokenApiAuthGitlabTokenCheckPostErrors];

export type CheckGitlabTokenApiAuthGitlabTokenCheckPostResponses = {
    /**
     * Successful Response
     */
    200: GitlabTokenCheckResponse;
};

export type CheckGitlabTokenApiAuthGitlabTokenCheckPostResponse =
    CheckGitlabTokenApiAuthGitlabTokenCheckPostResponses[keyof CheckGitlabTokenApiAuthGitlabTokenCheckPostResponses];

export type GetProfileApiAuthMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/auth/me";
};

export type GetProfileApiAuthMeGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type GetProfileApiAuthMeGetError =
    GetProfileApiAuthMeGetErrors[keyof GetProfileApiAuthMeGetErrors];

export type GetProfileApiAuthMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserProfileResponse;
};

export type GetProfileApiAuthMeGetResponse =
    GetProfileApiAuthMeGetResponses[keyof GetProfileApiAuthMeGetResponses];

export type GetProjectMembersApiProjectsProjectIdMembersGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * GitLab project ID
         */
        project_id: number;
    };
    query?: {
        /**
         * Page
         *
         * Page number for pagination
         */
        page?: number;
        /**
         * Per Page
         *
         * Number of members per page
         */
        per_page?: number;
        /**
         * Search
         *
         * Filter members by username or name
         */
        search?: string | null;
    };
    url: "/api/projects/{project_id}/members";
};

export type GetProjectMembersApiProjectsProjectIdMembersGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type GetProjectMembersApiProjectsProjectIdMembersGetError =
    GetProjectMembersApiProjectsProjectIdMembersGetErrors[keyof GetProjectMembersApiProjectsProjectIdMembersGetErrors];

export type GetProjectMembersApiProjectsProjectIdMembersGetResponses = {
    /**
     * Response Get Project Members Api Projects  Project Id  Members Get
     *
     * Successful Response
     */
    200: Array<MembersResponse>;
};

export type GetProjectMembersApiProjectsProjectIdMembersGetResponse =
    GetProjectMembersApiProjectsProjectIdMembersGetResponses[keyof GetProjectMembersApiProjectsProjectIdMembersGetResponses];

export type ListProjectsApiProjectsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * Page number for pagination
         */
        page?: number;
        /**
         * Per Page
         *
         * Number of projects per page
         */
        per_page?: number;
        /**
         * Search
         *
         * Filter projects by name or path
         */
        search?: string | null;
        /**
         * Membership
         *
         * Only return projects the authenticated user is a member of
         */
        membership?: boolean | null;
    };
    url: "/api/projects/";
};

export type ListProjectsApiProjectsGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListProjectsApiProjectsGetError =
    ListProjectsApiProjectsGetErrors[keyof ListProjectsApiProjectsGetErrors];

export type ListProjectsApiProjectsGetResponses = {
    /**
     * Response List Projects Api Projects  Get
     *
     * Successful Response
     */
    200: Array<ProjectsResponse>;
};

export type ListProjectsApiProjectsGetResponse =
    ListProjectsApiProjectsGetResponses[keyof ListProjectsApiProjectsGetResponses];

export type GetProjectApiProjectsProjectIdGetData = {
    body?: never;
    path: {
        /**
         * Project Id
         *
         * GitLab project ID
         */
        project_id: number;
    };
    query?: never;
    url: "/api/projects/{project_id}";
};

export type GetProjectApiProjectsProjectIdGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type GetProjectApiProjectsProjectIdGetError =
    GetProjectApiProjectsProjectIdGetErrors[keyof GetProjectApiProjectsProjectIdGetErrors];

export type GetProjectApiProjectsProjectIdGetResponses = {
    /**
     * Successful Response
     */
    200: ProjectsResponse;
};

export type GetProjectApiProjectsProjectIdGetResponse =
    GetProjectApiProjectsProjectIdGetResponses[keyof GetProjectApiProjectsProjectIdGetResponses];

export type ListGitlabUsersApiUsersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         *
         * Page number for pagination.
         */
        page?: number;
        /**
         * Per Page
         *
         * Number of users per page.
         */
        per_page?: number;
        /**
         * Humans
         *
         * Whether to include only human users.
         */
        humans?: boolean;
        /**
         * Search
         *
         * Search term to filter users by username or name.
         */
        search?: string | null;
    };
    url: "/api/users/";
};

export type ListGitlabUsersApiUsersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type ListGitlabUsersApiUsersGetError =
    ListGitlabUsersApiUsersGetErrors[keyof ListGitlabUsersApiUsersGetErrors];

export type ListGitlabUsersApiUsersGetResponses = {
    /**
     * Response List Gitlab Users Api Users  Get
     *
     * Successful Response
     */
    200: Array<GitLabUser>;
};

export type ListGitlabUsersApiUsersGetResponse =
    ListGitlabUsersApiUsersGetResponses[keyof ListGitlabUsersApiUsersGetResponses];

export type GetGitlabUserApiUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the GitLab user to retrieve.
         */
        user_id: number;
    };
    query?: never;
    url: "/api/users/{user_id}";
};

export type GetGitlabUserApiUsersUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetGitlabUserApiUsersUserIdGetError =
    GetGitlabUserApiUsersUserIdGetErrors[keyof GetGitlabUserApiUsersUserIdGetErrors];

export type GetGitlabUserApiUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: GitLabUser;
};

export type GetGitlabUserApiUsersUserIdGetResponse =
    GetGitlabUserApiUsersUserIdGetResponses[keyof GetGitlabUserApiUsersUserIdGetResponses];

export type GetUserTimelogsApiUsersUsernameTimelogsGetData = {
    body?: never;
    path: {
        /**
         * Username
         *
         * The username of the user to retrieve timelogs for.
         */
        username: string;
    };
    query: {
        /**
         * Start Time
         *
         * The start date for the timelog period.
         */
        start_time: string;
        /**
         * End Time
         *
         * The end date for the timelog period.
         */
        end_time: string;
        /**
         * First
         *
         * Number of timelogs to retrieve per page.
         */
        first?: number;
        /**
         * After
         *
         * Cursor for pagination to fetch the next set of timelogs.
         */
        after?: string | null;
    };
    url: "/api/users/{username}/timelogs";
};

export type GetUserTimelogsApiUsersUsernameTimelogsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type GetUserTimelogsApiUsersUsernameTimelogsGetError =
    GetUserTimelogsApiUsersUsernameTimelogsGetErrors[keyof GetUserTimelogsApiUsersUsernameTimelogsGetErrors];

export type GetUserTimelogsApiUsersUsernameTimelogsGetResponses = {
    /**
     * Successful Response
     */
    200: TimelogData;
};

export type GetUserTimelogsApiUsersUsernameTimelogsGetResponse =
    GetUserTimelogsApiUsersUsernameTimelogsGetResponses[keyof GetUserTimelogsApiUsersUsernameTimelogsGetResponses];

export type GetUserPerformanceApiPerformanceUsersUserIdGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the GitLab user.
         */
        user_id: number;
    };
    query: {
        /**
         * Start Date
         *
         * The start date for the performance period in ISO format.
         */
        start_date: string;
        /**
         * End Date
         *
         * The end date for the performance period in ISO format.
         */
        end_date: string;
    };
    url: "/api/performance/users/{user_id}";
};

export type GetUserPerformanceApiPerformanceUsersUserIdGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type GetUserPerformanceApiPerformanceUsersUserIdGetError =
    GetUserPerformanceApiPerformanceUsersUserIdGetErrors[keyof GetUserPerformanceApiPerformanceUsersUserIdGetErrors];

export type GetUserPerformanceApiPerformanceUsersUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: GeneralUserPerformance;
};

export type GetUserPerformanceApiPerformanceUsersUserIdGetResponse =
    GetUserPerformanceApiPerformanceUsersUserIdGetResponses[keyof GetUserPerformanceApiPerformanceUsersUserIdGetResponses];

export type GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             *
             * The ID of the GitLab project.
             */
            project_id: number;
            /**
             * User Id
             *
             * The ID of the GitLab user.
             */
            user_id: number;
        };
        query: {
            /**
             * Start Date
             *
             * The start date for the performance period in ISO format.
             */
            start_date: string;
            /**
             * End Date
             *
             * The end date for the performance period in ISO format.
             */
            end_date: string;
        };
        url: "/api/performance/projects/{project_id}/users/{user_id}";
    };

export type GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetErrors =
    {
        /**
         * Invalid credentials
         */
        401: ErrorResponseModel;
        /**
         * Resource not found
         */
        404: ErrorResponseModel;
        /**
         * Validation Error
         */
        422: HttpValidationError;
        /**
         * Internal Server Error
         */
        500: ErrorResponseModel;
    };

export type GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetError =
    GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetErrors[keyof GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetErrors];

export type GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetResponses =
    {
        /**
         * Successful Response
         */
        200: ProjectPerformanceResponse;
    };

export type GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetResponse =
    GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetResponses[keyof GetProjectPerformanceApiPerformanceProjectsProjectIdUsersUserIdGetResponses];

export type GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetData = {
    body?: never;
    path: {
        /**
         * User Id
         *
         * The ID of the GitLab user.
         */
        user_id: number;
    };
    query: {
        /**
         * Start Date
         *
         * The start date for the time spent period in ISO format.
         */
        start_date: string;
        /**
         * End Date
         *
         * The end date for the time spent period in ISO format.
         */
        end_date: string;
    };
    url: "/api/performanceusers/{user_id}/time-spent";
};

export type GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetErrors =
    {
        /**
         * Invalid credentials
         */
        401: ErrorResponseModel;
        /**
         * Resource not found
         */
        404: ErrorResponseModel;
        /**
         * Validation Error
         */
        422: HttpValidationError;
        /**
         * Internal Server Error
         */
        500: ErrorResponseModel;
    };

export type GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetError =
    GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetErrors[keyof GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetErrors];

export type GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetResponses =
    {
        /**
         * Successful Response
         */
        200: TimeSpentStats;
    };

export type GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetResponse =
    GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetResponses[keyof GetTimeSpentStatisticsApiPerformanceusersUserIdTimeSpentGetResponses];

export type GetUserSettingsApiPerformanceUsersUserIdSettingsGetData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: "/api/performance/users/{user_id}/settings";
};

export type GetUserSettingsApiPerformanceUsersUserIdSettingsGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type GetUserSettingsApiPerformanceUsersUserIdSettingsGetError =
    GetUserSettingsApiPerformanceUsersUserIdSettingsGetErrors[keyof GetUserSettingsApiPerformanceUsersUserIdSettingsGetErrors];

export type GetUserSettingsApiPerformanceUsersUserIdSettingsGetResponses = {
    /**
     * Successful Response
     */
    200: UserPerformanceSettings;
};

export type GetUserSettingsApiPerformanceUsersUserIdSettingsGetResponse =
    GetUserSettingsApiPerformanceUsersUserIdSettingsGetResponses[keyof GetUserSettingsApiPerformanceUsersUserIdSettingsGetResponses];

export type SetUserSettingsApiPerformanceUsersUserIdSettingsPostData = {
    body: UserPerfomanceSettingsRequest;
    path: {
        /**
         * User Id
         */
        user_id: number;
    };
    query?: never;
    url: "/api/performance/users/{user_id}/settings";
};

export type SetUserSettingsApiPerformanceUsersUserIdSettingsPostErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type SetUserSettingsApiPerformanceUsersUserIdSettingsPostError =
    SetUserSettingsApiPerformanceUsersUserIdSettingsPostErrors[keyof SetUserSettingsApiPerformanceUsersUserIdSettingsPostErrors];

export type SetUserSettingsApiPerformanceUsersUserIdSettingsPostResponses = {
    /**
     * Successful Response
     */
    200: UserPerformanceSettings;
};

export type SetUserSettingsApiPerformanceUsersUserIdSettingsPostResponse =
    SetUserSettingsApiPerformanceUsersUserIdSettingsPostResponses[keyof SetUserSettingsApiPerformanceUsersUserIdSettingsPostResponses];

export type GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetData =
    {
        body?: never;
        path: {
            /**
             * Project Id
             *
             * The ID of the GitLab project.
             */
            project_id: number;
        };
        query: {
            /**
             * Start Date
             *
             * The start date for the performance period in ISO format.
             */
            start_date: string;
            /**
             * End Date
             *
             * The end date for the performance period in ISO format.
             */
            end_date: string;
        };
        url: "/api/performance/projects/{project_id}";
    };

export type GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetErrors =
    {
        /**
         * Invalid credentials
         */
        401: ErrorResponseModel;
        /**
         * Validation Error
         */
        422: HttpValidationError;
        /**
         * Internal Server Error
         */
        500: ErrorResponseModel;
    };

export type GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetError =
    GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetErrors[keyof GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetErrors];

export type GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetResponses =
    {
        /**
         * Successful Response
         */
        200: GeneralProjectPerformance;
    };

export type GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetResponse =
    GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetResponses[keyof GetGeneralProjectPerformanceApiPerformanceProjectsProjectIdGetResponses];

export type ListSchedulesApiSchedulerReportsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/scheduler/reports";
};

export type ListSchedulesApiSchedulerReportsGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type ListSchedulesApiSchedulerReportsGetError =
    ListSchedulesApiSchedulerReportsGetErrors[keyof ListSchedulesApiSchedulerReportsGetErrors];

export type ListSchedulesApiSchedulerReportsGetResponses = {
    /**
     * Response List Schedules Api Scheduler Reports Get
     *
     * Successful Response
     */
    200: Array<ScheduledReportResponse>;
};

export type ListSchedulesApiSchedulerReportsGetResponse =
    ListSchedulesApiSchedulerReportsGetResponses[keyof ListSchedulesApiSchedulerReportsGetResponses];

export type CreateScheduleApiSchedulerReportsPostData = {
    body: ScheduledReportCreate;
    path?: never;
    query?: never;
    url: "/api/scheduler/reports";
};

export type CreateScheduleApiSchedulerReportsPostErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
    /**
     * Bad Gateway
     */
    502: ErrorResponseModel;
};

export type CreateScheduleApiSchedulerReportsPostError =
    CreateScheduleApiSchedulerReportsPostErrors[keyof CreateScheduleApiSchedulerReportsPostErrors];

export type CreateScheduleApiSchedulerReportsPostResponses = {
    /**
     * Successful Response
     */
    201: ScheduledReportResponse;
};

export type CreateScheduleApiSchedulerReportsPostResponse =
    CreateScheduleApiSchedulerReportsPostResponses[keyof CreateScheduleApiSchedulerReportsPostResponses];

export type DeleteScheduleApiSchedulerReportsScheduleIdDeleteData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: string;
    };
    query?: never;
    url: "/api/scheduler/reports/{schedule_id}";
};

export type DeleteScheduleApiSchedulerReportsScheduleIdDeleteErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteScheduleApiSchedulerReportsScheduleIdDeleteError =
    DeleteScheduleApiSchedulerReportsScheduleIdDeleteErrors[keyof DeleteScheduleApiSchedulerReportsScheduleIdDeleteErrors];

export type DeleteScheduleApiSchedulerReportsScheduleIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteScheduleApiSchedulerReportsScheduleIdDeleteResponse =
    DeleteScheduleApiSchedulerReportsScheduleIdDeleteResponses[keyof DeleteScheduleApiSchedulerReportsScheduleIdDeleteResponses];

export type GetScheduleApiSchedulerReportsScheduleIdGetData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         *
         * Mongo ObjectId of the schedule
         */
        schedule_id: string;
    };
    query?: never;
    url: "/api/scheduler/reports/{schedule_id}";
};

export type GetScheduleApiSchedulerReportsScheduleIdGetErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetScheduleApiSchedulerReportsScheduleIdGetError =
    GetScheduleApiSchedulerReportsScheduleIdGetErrors[keyof GetScheduleApiSchedulerReportsScheduleIdGetErrors];

export type GetScheduleApiSchedulerReportsScheduleIdGetResponses = {
    /**
     * Successful Response
     */
    200: ScheduledReportResponse;
};

export type GetScheduleApiSchedulerReportsScheduleIdGetResponse =
    GetScheduleApiSchedulerReportsScheduleIdGetResponses[keyof GetScheduleApiSchedulerReportsScheduleIdGetResponses];

export type UpdateScheduleApiSchedulerReportsScheduleIdPutData = {
    body: ScheduledReportUpdate;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: string;
    };
    query?: never;
    url: "/api/scheduler/reports/{schedule_id}";
};

export type UpdateScheduleApiSchedulerReportsScheduleIdPutErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateScheduleApiSchedulerReportsScheduleIdPutError =
    UpdateScheduleApiSchedulerReportsScheduleIdPutErrors[keyof UpdateScheduleApiSchedulerReportsScheduleIdPutErrors];

export type UpdateScheduleApiSchedulerReportsScheduleIdPutResponses = {
    /**
     * Successful Response
     */
    200: ScheduledReportResponse;
};

export type UpdateScheduleApiSchedulerReportsScheduleIdPutResponse =
    UpdateScheduleApiSchedulerReportsScheduleIdPutResponses[keyof UpdateScheduleApiSchedulerReportsScheduleIdPutResponses];

export type SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostData = {
    body?: never;
    path: {
        /**
         * Schedule Id
         */
        schedule_id: string;
    };
    query?: never;
    url: "/api/scheduler/reports/{schedule_id}/send-now";
};

export type SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostErrors = {
    /**
     * Invalid credentials
     */
    401: ErrorResponseModel;
    /**
     * Resource not found
     */
    404: ErrorResponseModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
    /**
     * Internal Server Error
     */
    500: ErrorResponseModel;
};

export type SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostError =
    SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostErrors[keyof SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostErrors];

export type SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostResponses = {
    /**
     * Response Send Schedule Now Api Scheduler Reports  Schedule Id  Send Now Post
     *
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostResponse =
    SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostResponses[keyof SendScheduleNowApiSchedulerReportsScheduleIdSendNowPostResponses];

export type HealthHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/health";
};

export type HealthHealthGetResponses = {
    /**
     * Response Health Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type HealthHealthGetResponse =
    HealthHealthGetResponses[keyof HealthHealthGetResponses];
