// This file is auto-generated by @hey-api/openapi-ts

import { z } from "zod";

/**
 * Commits
 *
 * Details of a Commit.
 */
export const zCommits = z.object({
    title: z.string(),
    message: z.string(),
    web_url: z.string(),
    authored_date: z.iso.datetime(),
    additions: z.int(),
    deletions: z.int(),
});

/**
 * ErrorResponseModel
 *
 * Standard error response model.
 */
export const zErrorResponseModel = z.object({
    detail: z.string(),
});

/**
 * GitLabConfigRequest
 *
 * Payload for configuring the GitLab admin token and URL.
 */
export const zGitLabConfigRequest = z.object({
    gitlab_url: z.url().min(1),
    gitlab_admin_token: z.string().min(1),
});

/**
 * GitLabConfigResponse
 *
 * Response after updating the GitLab configuration.
 */
export const zGitLabConfigResponse = z.object({
    gitlab_user_info: z.record(z.string(), z.unknown()),
    gitlab_url: z.url().min(1),
});

/**
 * LoginRequest
 *
 * Incoming payload for user login or first-time bootstrap.
 */
export const zLoginRequest = z.object({
    username: z.string().min(3).max(128),
    password: z.string().min(6).max(256),
    gitlab_url: z.optional(z.union([z.url().min(1), z.null()])),
    gitlab_admin_token: z.optional(z.union([z.string().min(1), z.null()])),
});

/**
 * LoginResponse
 *
 * Token response returned after successful authentication.
 */
export const zLoginResponse = z.object({
    access_token: z.string(),
    token_type: z.optional(z.string()).default("bearer"),
    username: z.string(),
    expires_at: z.iso.datetime(),
    gitlab_configured: z.boolean(),
    gitlab_user_info: z.optional(
        z.union([z.record(z.string(), z.unknown()), z.null()]),
    ),
});

/**
 * LogoutResponse
 *
 * Acknowledgement returned after logout.
 */
export const zLogoutResponse = z.object({
    success: z.optional(z.boolean()).default(true),
});

/**
 * MembersResponse
 *
 * Response schema for GitLab project members.
 */
export const zMembersResponse = z.object({
    id: z.int(),
    username: z.string(),
    name: z.string(),
    web_url: z.string(),
    avatar_url: z.optional(z.union([z.string(), z.null()])),
    state: z.string(),
    access_level: z.int(),
    access_level_name: z.string(),
});

/**
 * MrDetails
 *
 * Details of a Merge Request.
 */
export const zMrDetails = z.object({
    iid: z.int(),
    title: z.string(),
    description: z.string(),
    web_url: z.string(),
    created_at: z.iso.datetime(),
    state: z.string(),
    commits_count: z.int(),
    commits: z.array(zCommits),
});

/**
 * ProjectsResponse
 *
 * Response schema for GitLab projects.
 */
export const zProjectsResponse = z.object({
    id: z.int(),
    name: z.string(),
    name_with_namespace: z.string(),
    path_with_namespace: z.string(),
    web_url: z.string(),
    avatar_url: z.optional(z.union([z.string(), z.null()])),
    created_at: z.iso.datetime(),
});

/**
 * UserPerformanceResponse
 *
 * Response model for user performance data.
 */
export const zUserPerformanceResponse = z.object({
    username: z.string(),
    project_path_name: z.string(),
    since: z.iso.datetime(),
    until: z.iso.datetime(),
    total_commits: z.int(),
    total_additions: z.int(),
    total_deletions: z.int(),
    total_changes: z.int(),
    total_mr_contributed: z.int(),
    daily_commit_counts: z.record(z.string(), z.int()),
    daily_additions: z.record(z.string(), z.int()),
    daily_deletions: z.record(z.string(), z.int()),
    daily_changes: z.record(z.string(), z.int()),
    merge_requests: z.array(zMrDetails),
    llm_prompt_suggestion: z.string(),
    prompt_tokens: z.int(),
    calculated_at: z.iso.datetime(),
});

/**
 * UserProfileResponse
 *
 * Basic profile snapshot for the single configured user.
 */
export const zUserProfileResponse = z.object({
    username: z.string(),
    gitlab_user_info: z.optional(
        z.union([z.record(z.string(), z.unknown()), z.null()]),
    ),
    gitlab_url: z.optional(z.union([z.url().min(1), z.null()])),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.optional(z.array(zValidationError)),
});

export const zLoginAuthLoginPostData = z.object({
    body: zLoginRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
    headers: z.optional(
        z.object({
            "User-Agent": z.optional(z.union([z.string(), z.null()])),
        }),
    ),
});

/**
 * Successful Response
 */
export const zLoginAuthLoginPostResponse = zLoginResponse;

export const zLogoutAuthLogoutPostData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zLogoutAuthLogoutPostResponse = zLogoutResponse;

export const zUpdateGitlabConfigurationAuthGitlabPostData = z.object({
    body: zGitLabConfigRequest,
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zUpdateGitlabConfigurationAuthGitlabPostResponse =
    zGitLabConfigResponse;

export const zGetProfileAuthMeGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetProfileAuthMeGetResponse = zUserProfileResponse;

export const zGetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetData =
    z.object({
        body: z.optional(z.never()),
        path: z.object({
            user_id: z.int(),
            project_id: z.string(),
        }),
        query: z.object({
            start_date: z.iso.datetime(),
            end_date: z.iso.datetime(),
        }),
    });

/**
 * Successful Response
 */
export const zGetUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceGetResponse =
    zUserPerformanceResponse;

export const zRefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostData =
    z.object({
        body: z.optional(z.never()),
        path: z.object({
            user_id: z.int(),
            project_id: z.string(),
        }),
        query: z.object({
            start_date: z.iso.datetime(),
            end_date: z.iso.datetime(),
        }),
    });

/**
 * Successful Response
 */
export const zRefreshUserPerformanceUserPerformanceProjectsProjectIdUsersUserIdPerformanceRefreshPostResponse =
    zUserPerformanceResponse;

export const zGetProjectMembersGitlabProjectsProjectIdMembersGetData = z.object(
    {
        body: z.optional(z.never()),
        path: z.object({
            project_id: z.int(),
        }),
        query: z.optional(
            z.object({
                page: z.optional(z.int().gte(1)).default(1),
                per_page: z.optional(z.int().gte(1).lte(100)).default(20),
                search: z.optional(z.union([z.string(), z.null()])),
            }),
        ),
    },
);

/**
 * Response Get Project Members Gitlab Projects  Project Id  Members Get
 *
 * Successful Response
 */
export const zGetProjectMembersGitlabProjectsProjectIdMembersGetResponse =
    z.array(zMembersResponse);

export const zListProjectsGitlabProjectsGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(
        z.object({
            page: z.optional(z.int().gte(1)).default(1),
            per_page: z.optional(z.int().gte(1).lte(100)).default(20),
            search: z.optional(z.union([z.string(), z.null()])),
            membership: z.optional(z.union([z.boolean(), z.null()])),
        }),
    ),
});

/**
 * Response List Projects Gitlab Projects Get
 *
 * Successful Response
 */
export const zListProjectsGitlabProjectsGetResponse =
    z.array(zProjectsResponse);

export const zHealthHealthGetData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.never()),
});

/**
 * Response Health Health Get
 *
 * Successful Response
 */
export const zHealthHealthGetResponse = z.record(z.string(), z.string());
